@startuml
left to right direction
actor Empleado
actor Gerente_RRHH as "Gerente RRHH"
actor Oficial_Nomina as "Oficial de Nómina"
actor Administrador
actor Sistema

rectangle "Sistema de Gestión de Empleados" {
  Empleado --> (Iniciar Sesión)
  Empleado --> (Ver Perfil)
  Empleado --> (Actualizar Perfil)
  Empleado --> (Solicitar Permiso)
  Empleado --> (Ver Recibo de Pago)
  Empleado --> (Inscribirse en Capacitación)
  Gerente_RRHH --> (Agregar Empleado)
  Gerente_RRHH --> (Actualizar Información del Empleado)
  Gerente_RRHH --> (Aprobar Permiso)
  Gerente_RRHH --> (Realizar Evaluación de Desempeño)
  Oficial_Nomina --> (Procesar Nómina)
  Oficial_Nomina --> (Generar Recibos de Pago)
  Administrador --> (Gestionar Usuarios)
  Administrador --> (Configurar Sistema)
  Administrador --> (Realizar Auditorías)
  Administrador --> (Respaldar Datos)
}

@enduml
