version: '3.8'

services:

  java-app:
    image: admin-employer:1.0
    container_name: java-app
    build: .
    ports:
      - "8080:8080"
    environment:
       DATASOURCE_URL: "jdbc:postgresql://java-db:5432/postgres"
       DATASOURCE_USERNAME: "postgres"
       DATASOURCE_PASSWORD: "postgres"
  
    depends_on:
      - java-db

  java-db:
    container_name: java-db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      